server:
  intranet:
    ip: 192.168.x.x,10.161.x.x,10.192.x.x
  port: 7055
  error:
    include-message: always
  servlet:
    context-path: /interfaceManager
    register-default-servlet: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      tracking-modes: COOKIE
  tomcat:
    uri-encoding: UTF-8
eureka:
  server:
    enable-self-preservation: false # 关闭自我保护功能，默认为true
    eviction-interval-timer-in-ms: 600000
    useReadOnlyResponseCache: false
  dashboard:
    enabled: false # 启用服务面板
    path: / # 服务面板路径
  client:
    service-url:
      defaultZone: http://localhost:8080/interfaceManager/eureka/  # Eureka服务器地址本机地址
    fetch-registry: false  # 是否从Eureka服务器获取注册信息
    register-with-eureka: false  # 是否注册自身到Eureka服务器
spring:
  eureka:
    token: "admin:123"
  application:
    name: interfaceManager
  aop:
    auto: false
    proxy-target-class: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    generate-unique-name: false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          log-slow-sql: true
          mergeSql: true
          slow-sql-millis: 3000
        wall:
          config:
            drop-table-allow: true
          enabled: true
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
        allow: 127.0.0.1
      web-stat-filter:
        enabled: false
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
      y9-public:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/y9_interface?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false
        username: root
        password: root
        initialSize: 1
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 100
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 1
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        useGlobalDataSourceStat: true
        validationQuery: SELECT 1 FROM DUAL
  jmx:
    default-domain: interfaceManager
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 100
        show_sql: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      auto-commit-interval: 1000
      enable-auto-commit: false
      group-id: y9risedata-server
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  redis:
    database: 8
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      shutdown-timeout: 100ms
    password: y9i-83204585
    port: 6379
    ssl: false
    timeout: 10000
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 1000MB
y9:
  interfacePath: D:\\interfaceFile
  systemName: interfaceManager
  common:
    idEnabled: 0
    kafkaEnabled: false
  feature:
    log:
      enabled: false
    jpa:
      packagesToScanEntityPublic: net.risesoft.y9public.entity
      packagesToScanEntityTenant: net.risesoft.entity
      packagesToScanRepositoryPublic: net.risesoft.y9public.repository
      packagesToScanRepositoryTenant: net.risesoft.repository
    session:
      redis:
        enabled: true
        maxInactiveIntervalInSeconds: 3600
    security:
      enabled: true
      cors:
        allowCredentials: true
        allowedOriginPatterns:
          - https://*.youshengyun.com
          - http://*.youshengyun.com
          - http://localhost:7055
          - http://localhost:8080
          - http://localhost:7070
          - http://127.0.0.1:7055
      xss:
        ignoreParam:
          - ID
          - properties
          - url
      csrf:
        acceptedReferer:
          - 127.0.0.1
          - localhost
          - vue.youshengyun.com
          - test.youshengyun.com
          - demo.youshengyun.com
    oauth2:
      resource:
        enabled: true
        saveLogMessage: false
        saveOnlineMessage: false
        allowBasicAuthentication: true
        allowFormEncodedBodyParameter: true
        allowUriQueryParameter: true
        protectedUrlPatterns: /api/*
        opaque:
          client-id: clientid
          client-secret: secret
          introspection-uri: http://localhost:7055/sso/oauth2.0/introspect
          profile-uri: http://localhost:7055/sso/oauth2.0/profile
